spring:
  datasource:
    url: jdbc:mysql://localhost:3306/image?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: haoyin31268366
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5  
    minIdle: 5
    maxActive: 20  
    maxWait: 60000
server:
   port: 8088
localConfig:
  fileUploadPath: /static/INITIAL
  imageUploadPath: /static/haoyin_static
  payImages: /payImages
  imageUploadPathRead: http://static.haoyin.com
yeepay:
  redirectUrl: http://initial.haoyin.com/yeePay/sync.html
  notifyUrl: http://initial.haoyin.com/yeePay/notify.html
